// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw87UwwFYQEUiyxibBbpXrapQmP5LyJXI',
    appId: '1:947332750079:web:4f1a72950607463c0e0aca',
    messagingSenderId: '947332750079',
    projectId: 'fir-second-bbdd6',
    authDomain: 'fir-second-bbdd6.firebaseapp.com',
    storageBucket: 'fir-second-bbdd6.appspot.com',
    measurementId: 'G-CBKZGVVY1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVRwooZX2BjkRKk_HqhXyXIX--Ly1dh6M',
    appId: '1:947332750079:android:b2854815ebeb80050e0aca',
    messagingSenderId: '947332750079',
    projectId: 'fir-second-bbdd6',
    storageBucket: 'fir-second-bbdd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6DR0eoSp9t-qBvj6OsMBfhqNPN2CWVxk',
    appId: '1:947332750079:ios:8183119c0ff21f6a0e0aca',
    messagingSenderId: '947332750079',
    projectId: 'fir-second-bbdd6',
    storageBucket: 'fir-second-bbdd6.appspot.com',
    iosBundleId: 'com.example.firebasesecond',
  );
}
